# Generated by Django 5.0.6 on 2024-05-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='chat_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
